name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: curl example.com
        run: curl http://example.com
      - name: run helmfile
        run: helmfile
      - name: curl kubernetes endpoint
        run: curl -k https://abcke.local:6443